### ISSUE TITLE
Automatic deployments commit with "$USER_NAME"

### ISSUE THREAD

**Issue by Guria** [northbrookjs/northbrook#31]
Seems smth wrong with setup on your repo.
Release commits made by $USER_NAME

**Comment by TylorS** [comment]
Thanks for pointing this out, I'm surprised it even works to be honest. :)

Will fix it soon, it's a part of the [automatic deployments I have setup](https://github.com/northbrookjs/northbrook/blob/master/.scripts/deploy.sh#L5), I'm pretty sure I know the solution

**Comment by TylorS** [comment]
Fixed in 2.2.4
