### ISSUE TITLE
Generated Changelog.md has inactive links

### ISSUE THREAD

**Issue by Guria** [northbrookjs/northbrook#32]
**Code to reproduce the issue:**
none

**Expected behavior:**
Links rendered as correct `<a href>` in CHANGELOG.MD

**Actual behavior:**
List is indented which causes to wrap it in some sort of block.
Links inside this block rendered as raw md representation.

**Versions of packages used:**
2.2.3

**Comment by Guria** [comment]
![image](https://cloud.githubusercontent.com/assets/36270/17988109/2c50604a-6b35-11e6-8324-48670237d90f.png)

**Comment by TylorS** [comment]
I sort of did the indenting on purpose, but I don't remember my reasoning. To be honest, chngelogs have been one of my lower priorities, and I didn't realize that indenting broke the way links worked. 

Will place this high on my to-do list

**Comment by TylorS** [comment]
Fixed in v2.2.4
