### ISSUE TITLE
Requires `repository` field in package's manifests

### ISSUE THREAD

**Issue by wclr** [northbrookjs/northbrook#72]
If no `repository` field in package's manifests errors:
(node:13280) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'ur l' of undefined

Should probably give a warning on such cases.

**Comment by TylorS** [comment]
This is likely still an error in some way. Will try to write some tests for it soon.

**Comment by TylorS** [comment]
This should be fixed in the latest version (previous actually).
