### ISSUE TITLE
Allow initial publish of scoped public without error

### ISSUE THREAD

**Issue by wclr** [northbrookjs/northbrook#74]
Allow initial publish of scoped public without error. Thing this should be allowed.

**Comment by Frikki** [comment]
What does that even mean?

**Comment by wclr** [comment]
@Frikki https://github.com/northbrookjs/northbrook#options see `--skip-npm` option

**Comment by Frikki** [comment]
@whitecolor Are you asking for an option `--access=public`?

**Comment by wclr** [comment]
I say that this should be handled. The problem is that workflow is interrupted with an error when trying to release. This should not be just the case.

**Comment by Frikki** [comment]
You could make a PR for the feature you’d like to see.

**Comment by wclr** [comment]
I put it here. Not to forget)

**Comment by TylorS** [comment]
This is fxied in v4 release.
