### ISSUE TITLE
export execute?

### ISSUE THREAD

**Issue by anilanar** [northbrookjs/northbrook#99]
Spawning child processes is probably the most needed functionality by plugins. Would it make sense to export it from `northbrook` so that plugins can use it instead of implementing it themselves?

**Comment by TylorS** [comment]
This is already achievable (yet undocumented) by `import { execute } from 'northbrook/helpers'`

**Comment by anilanar** [comment]
You cannot import from `northbrook/helpers` if you use es6 module system, mind if I make a PR?
